services:

  backend:
    image: react-django-task-app/backend:latest
    container_name: backend
    restart: unless-stopped
    tty: true
    depends_on:
      - postgres
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app:ro
      - backend-venv:/usr/src/app/venv
    env_file: ./.env
    environment:
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=qwerty123
      - EMAIL_HOST=mailhog
    networks:
      - app-network

  postgres:
    image: postgres
    container_name: postgres

    restart: unless-stopped

    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=qwerty123
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - app-network

volumes:
  postgres-db:
  backend-venv: 

networks:
  app-network:
    driver: bridge
